/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppBooks {
    }
    interface AppCart {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppBooksElement extends Components.AppBooks, HTMLStencilElement {
    }
    var HTMLAppBooksElement: {
        prototype: HTMLAppBooksElement;
        new (): HTMLAppBooksElement;
    };
    interface HTMLAppCartElement extends Components.AppCart, HTMLStencilElement {
    }
    var HTMLAppCartElement: {
        prototype: HTMLAppCartElement;
        new (): HTMLAppCartElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-books": HTMLAppBooksElement;
        "app-cart": HTMLAppCartElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppBooks {
    }
    interface AppCart {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-books": AppBooks;
        "app-cart": AppCart;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-books": LocalJSX.AppBooks & JSXBase.HTMLAttributes<HTMLAppBooksElement>;
            "app-cart": LocalJSX.AppCart & JSXBase.HTMLAttributes<HTMLAppCartElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
